networks:
    nginx-php-mysql-redis:

services:

    # nginx
    nginx-service:
        image: nginx:stable-alpine
        container_name: nginx-container
        ports:
            - "8081:80"
        volumes:
            - ./app:/var/www/assessment
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php-service
            - mysql-service
            - redis-service
        networks:
            - nginx-php-mysql-redis

    # php
    php-service:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: php-container
        ports:
            - "8080:80"
        volumes:
            - ./app:/var/www/assessment
        networks:
            - nginx-php-mysql-redis

    # MySQL server
    mysql-service:
        image: mysql:8.0.38
        container_name: mysql-container
        ports:
            - "4306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_PASSWORD: secret
            MYSQL_DATABASE: assessment
            MYSQL_USER: zia
        networks:
            - nginx-php-mysql-redis

    # MySQL client
    mysql-client:
        image: mysql:8.0
        container_name: mysql-client-container
        command: ["sleep", "infinity"]
        networks:
            - nginx-php-mysql-redis
    
    # redis
    redis-service:
        image: redis:latest
        container_name: redis_container
        ports:
            - "6379:6379"
        networks:
            - nginx-php-mysql-redis